// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyA66kZJxATGhAQOk-vd57bH2V-aBoD4',
    appId: '1:586243403586:web:a6b5bf5e9a59b593d722db',
    messagingSenderId: '586243403586',
    projectId: 'keitask-management',
    authDomain: 'keitask-management.firebaseapp.com',
    storageBucket: 'keitask-management.firebasestorage.app',
    measurementId: 'G-2QSDYR1BLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1qUJSZiRq8uiMmd1VeIJVzyzCLC3-f2c',
    appId: '1:586243403586:android:62990d8c7bf8a599d722db',
    messagingSenderId: '586243403586',
    projectId: 'keitask-management',
    storageBucket: 'keitask-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRcfL2y-PT6J-VQuHsz7-ed_tI5JgM_zM',
    appId: '1:586243403586:ios:b5256f0e735efd52d722db',
    messagingSenderId: '586243403586',
    projectId: 'keitask-management',
    storageBucket: 'keitask-management.firebasestorage.app',
    iosBundleId: 'com.example.keitaskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRcfL2y-PT6J-VQuHsz7-ed_tI5JgM_zM',
    appId: '1:586243403586:ios:b5256f0e735efd52d722db',
    messagingSenderId: '586243403586',
    projectId: 'keitask-management',
    storageBucket: 'keitask-management.firebasestorage.app',
    iosBundleId: 'com.example.keitaskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNyA66kZJxATGhAQOk-vd57bH2V-aBoD4',
    appId: '1:586243403586:web:51ed7cdaff73dfced722db',
    messagingSenderId: '586243403586',
    projectId: 'keitask-management',
    authDomain: 'keitask-management.firebaseapp.com',
    storageBucket: 'keitask-management.firebasestorage.app',
    measurementId: 'G-PFLKQXGGEL',
  );
}
